### ISSUE TITLE
ResponseHeaders aren't propagating - possible fix haxe.http.HttpJs.hx

### ISSUE THREAD

**Issue by hoseyjoe** [core-haxe/http#7]
I was using an api that auto pagination. They pass the page count in headers and I am getting null on response.headers  
https://docs.gitlab.com/ee/api/rest/index.html#pagination (looking for x-total-pages)

Anyways I added this to fix it in haxe.http.HttpJs.hx for JS client

line 77
```
if (s != null && s >= 200 && s < 400) {
	req = null;
	var heads = r.getAllResponseHeaders().split("\r\n");
	for (h in heads){
		if (h!=null && h!=""){
			var s = h.split(":");
			if (responseHeaders == null)
				responseHeaders=[];
			responseHeaders.set(s[0], (s.length > 1) ? s[1]: null);
		}
	}
	success(Bytes.ofData(r.response));
}
```

**Comment by ianharrigan** [comment]
PR? :)

**Comment by hoseyjoe** [comment]
Probably could be better written...but there it is 
https://github.com/core-haxe/http/pull/8
